"""Persistence port for audio jobs."""

from datetime import datetime
from typing import Protocol

from ..models import AudioJob, JobError, JobResult


class JobRepository(Protocol):
    def create(self, job: AudioJob) -> None: ...
    def get(self, job_id: str) -> AudioJob | None: ...
    def claim(self, job_id: str, worker_id: str, lease_until: datetime) -> AudioJob | None: ...
    def mark_completed(self, job_id: str, result: JobResult) -> None: ...
    def mark_failed(self, job_id: str, error: JobError) -> None: ...
