"""Workspace allocation port for persisted jobs."""

from datetime import datetime
from pathlib import Path
from typing import Protocol


class JobStorage(Protocol):
    def incoming_path(self, job_id: str, created_at: datetime, extension: str) -> Path: ...
    def prepare_processing(self, job_id: str) -> Path: ...
    def results_directory(self, job_id: str, created_at: datetime) -> Path: ...
    def failed_directory(self, job_id: str, created_at: datetime) -> Path: ...
    def cleanup_processing(self, job_id: str) -> None: ...
