"""Persistence port for the AudioJob aggregate."""

from datetime import datetime
from typing import Protocol

from ...domain.models import AudioJob


class JobRepository(Protocol):
    async def create(self, job: AudioJob) -> None: ...
    async def get(self, job_id: str) -> AudioJob | None: ...
    async def claim(self, job_id: str, worker_id: str, lease_until: datetime) -> AudioJob | None: ...
    async def save(self, job: AudioJob) -> None: ...
